### ISSUE TITLE
 Issue 57808: libssh: Coverage build failure 

### ISSUE THREAD

**Issue by Jakuje** [google/oss-fuzz#10136]
Couple of weeks ago we got an issue about coverage build failure:

https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=57808

The log does not show anything useful and if I see right the only failure is the following part in the end of the log:

```
Starting Step #16
Step #16: Already have image (with digest): gcr.io/cloud-builders/gsutil
Step #16: CommandException: No URLs matched: /workspace/srcmap.json
Finished Step #16
ERROR
ERROR: build step 16 "gcr.io/cloud-builders/gsutil" failed: step exited with non-zero status: 1
```
which I have no idea what does it mean nor if that is something that can be fixed from our side. Around the time when the issue was filled, there were no changes to the repository master branch for more than one week.

Is it some issue on the oss-fuzz side or did I miss some part of the coverage log?

**Comment by Alan32Liu** [comment]
This is strange: I am unable to reproduce this build failure locally via:
```
python infra/helper.py build_image libssh
python infra/helper.py build_fuzzers --sanitizer address libssh
```
Recent [build logs](https://oss-fuzz-build-logs.storage.googleapis.com/index.html#libssh)  seem fine, too.

Requesting help from @oliverchang.

**Comment by jonathanmetzman** [comment]
Dongge this is a coverage build failure. Our UI https://oss-fuzz-build-logs.storage.googleapis.com/index.html#libssh is reporting a failure (I think the UI is semi broken though, it shows me the fuzzer build logs instead of the coverage build ones).

**Comment by Alan32Liu** [comment]
Thanks!
Re. the UI issue, do we use an identical URL (https://oss-fuzz-build-logs.storage.googleapis.com/index.html#libssh) for both the fuzzer build and coverage build (and the introspector build)?

**Comment by jonathanmetzman** [comment]
> Thanks! Re. the UI issue, do we use an identical URL (https://oss-fuzz-build-logs.storage.googleapis.com/index.html#libssh) for both the fuzzer build and coverage build (and the introspector build)?

Yup

**Comment by Jakuje** [comment]
Got another ping today about the failed coverage, but I still do not see any failure in the coverage build log that I could fix. Can you clarify if there is something I can do or if this is some infra issue?

**Comment by Alan32Liu** [comment]
A quick update:
`srcmap` works fine in `gcr.io/oss-fuzz/libssh` when I tested it locally.
[The command](https://github.com/google/oss-fuzz/blob/85f7a5e1d793628b675312b6c9134458453e3f1e/infra/build/functions/build_lib.py#L444) prints the same outputs and saves the file in the indented directory.

I will check if some code accidentally removed that file later.

**Comment by Jakuje** [comment]
Three days ago, the coverage build was successful. Not sure if anything changed since then on your side.
Lets keep it open if it will re-open or if we will get a new reports.

**Comment by Alan32Liu** [comment]
Thanks, that's good to hear!
I did not change anything, though, because I could not figure out why that `srcmap.json` was missing in the first place.
I don't think we have deployed any new ClusterFuzz commit.
But there are changes to OSS-Fuzz.

I am a bit inclined to close it and re-open it if that (or similar) error happens.
WDYT @jonathanmetzman ?

**Comment by Alan32Liu** [comment]
Interesting, I don't think anything has changed.
Would this be non-deterministic somehow? I will continue look into this when I have time.

**Comment by Jakuje** [comment]
And another one after the previous one was closed:

https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=60875#c1

The build log does not show anything usable either ...

**Comment by Jakuje** [comment]
ping? Any update on this?

I just noticed one more exception coming from most of the steps:

```
Step #6: CommandException: 1 files/objects could not be removed.
```

any idea what could this mean? Is there a way to get more verbose logs to see what was the actual object?

We are spammed with the mails about coverage build failure for well over 6 months every week.

**Comment by Jakuje** [comment]
Ping? Any update 6 months later? The previous message is still present in the coverage builds, but I do not see what is the its cause.

We are being spammed by the bugzilla every week about this: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=67123

**Comment by jonathanmetzman** [comment]
> Ping? Any update 6 months later? The previous message is still present in the coverage builds, but I do not see what is the its cause.

We generally don't have the bandwidth to investigate the unique behavior of individual projects, there's over 1000 in OSS-Fuzz.
It looks like this file is written to /workspace early on in the build process and later gets deleted. Any idea why this happens? It seems to be unique to libssh.

**Comment by Jakuje** [comment]
> This is interesting, because the last passing coverage build had libfuzzer failures: https://oss-fuzz-build-logs.storage.googleapis.com/log-f3cd498e-85bc-409e-bb32-f2f32b9e75d0.txt

Thank you for having a look into this! This input is a string `include./*/*2`, which is parsed by the libssh config parser attempting to read the content of the the `/` directory of the container where it runs, which can result in any unexpected issues.

As a workaround, we can disable some subset of the code attempting to touch the content of the container while parsing one configuration file with some limitation on what will actually be tested.

> I am not an OSS-Fuzz maintainer, so I don't have any further insight, but my recommendation would be to fix the outstanding non-coverage related issues listed in https://bugs.chromium.org/p/oss-fuzz/issues/list?q=proj%3Alibssh&can=2

I think I already tried that, but these are some pattern matching stuff that I was not able to limit reasonably more, but I will certainly try again.

>  It looks like this srcmap file is written to /workspace early on in the build process and later gets deleted. Any idea why this happens? It seems to be unique to libssh.

Only case I can think of that could cause it would be if the fuzzers would be running there with inputs that would contain execution of `rm srcmap`. Given the richness of the OpenSSH configuration file and matching syntax, this is what would cause execution of this, which is certainly not ideal and might be a good candidate to skip at least during the fuzzing builds.

**Comment by Jakuje** [comment]
Thank you for having a look into this. Could it be an issue I describe and would it be a good idea to prevent the fuzzers to run `exec` like this? If so, I have a MR that should avoid this

https://gitlab.com/libssh/libssh-mirror/-/merge_requests/509

I suspect this could be something like this, but I do not want to shovel through the corpus.

If you think it could help, we can try to merge it, provide this flag in the fuzzers build and see if it will help.
