### ISSUE TITLE
Somethingi wrong with the build service

### ISSUE THREAD

**Issue by tytso** [google/oss-fuzz#6966]
The build failure reported at: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=41738 was:

Step #3 - "compile-afl-address-x86_64": checking for gcc... /src/aflplusplus/afl-clang-fast
Step #3 - "compile-afl-address-x86_64": checking whether the C compiler works... no
Step #3 - "compile-afl-address-x86_64": configure: error: in `/src/e2fsprogs':
Step #3 - "compile-afl-address-x86_64": configure: error: C compiler cannot create executables

That looks like a failure in the oss-fuzz infrastructure?

**Comment by DavidKorczynski** [comment]
This is https://github.com/google/oss-fuzz/issues/6957 which has been fixed, but it should take a day or so before it gets triggered

**Comment by MarcoFalke** [comment]
Let us know if this isn't fixed in the next 25 hours (after  #6970)

**Comment by MarcoFalke** [comment]
Can be closed?

**Comment by pitrou** [comment]
The latest builds (7/12) are still failing for many projects.

**Comment by pitrou** [comment]
For example:
```
Step #3 - "compile-afl-address-x86_64": -- Check for working C compiler: /src/aflplusplus/afl-clang-fast
Step #3 - "compile-afl-address-x86_64": -- Check for working C compiler: /src/aflplusplus/afl-clang-fast - broken
Step #3 - "compile-afl-address-x86_64": CMake Error at /usr/local/share/cmake-3.21/Modules/CMakeTestCCompiler.cmake:69 (message):
Step #3 - "compile-afl-address-x86_64":   The C compiler
Step #3 - "compile-afl-address-x86_64": 
Step #3 - "compile-afl-address-x86_64":     "/src/aflplusplus/afl-clang-fast"
Step #3 - "compile-afl-address-x86_64": 
Step #3 - "compile-afl-address-x86_64":   is not able to compile a simple test program.
Step #3 - "compile-afl-address-x86_64": 
Step #3 - "compile-afl-address-x86_64":   It fails with the following output:
Step #3 - "compile-afl-address-x86_64": 
Step #3 - "compile-afl-address-x86_64":     Change Dir: /work/CMakeFiles/CMakeTmp
Step #3 - "compile-afl-address-x86_64":     
Step #3 - "compile-afl-address-x86_64":     Run Build Command(s):/usr/bin/ninja cmTC_9f147 && [1/2] Building C object CMakeFiles/cmTC_9f147.dir/testCCompiler.c.o
Step #3 - "compile-afl-address-x86_64":     FAILED: CMakeFiles/cmTC_9f147.dir/testCCompiler.c.o 
Step #3 - "compile-afl-address-x86_64":     /src/aflplusplus/afl-clang-fast   -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -o CMakeFiles/cmTC_9f147.dir/testCCompiler.c.o -c /work/CMakeFiles/CMakeTmp/testCCompiler.c
Step #3 - "compile-afl-address-x86_64":     error: unable to load plugin '/src/aflplusplus/cmplog-switches-pass.so': '/src/aflplusplus/cmplog-switches-pass.so: cannot open shared object file: No such file or directory'
Step #3 - "compile-afl-address-x86_64":     error: unable to load plugin '/src/aflplusplus/split-switches-pass.so': '/src/aflplusplus/split-switches-pass.so: cannot open shared object file: No such file or directory'
Step #3 - "compile-afl-address-x86_64":     error: unable to load plugin '/src/aflplusplus/SanitizerCoveragePCGUARD.so': '/src/aflplusplus/SanitizerCoveragePCGUARD.so: cannot open shared object file: No such file or directory'
Step #3 - "compile-afl-address-x86_64":     error: unable to load plugin '/src/aflplusplus/cmplog-instructions-pass.so': '/src/aflplusplus/cmplog-instructions-pass.so: cannot open shared object file: No such file or directory'
Step #3 - "compile-afl-address-x86_64":     error: unable to load plugin '/src/aflplusplus/cmplog-routines-pass.so': '/src/aflplusplus/cmplog-routines-pass.so: cannot open shared object file: No such file or directory'
Step #3 - "compile-afl-address-x86_64":     ninja: build stopped: subcommand failed.
```
(https://oss-fuzz-build-logs.storage.googleapis.com/log-12f1d8f7-f4c3-4143-829c-3ae637d002b5.txt)

**Comment by MarcoFalke** [comment]
This should be fixed with 9d864ee0e38e62b33916bc0725fd34b278394989 (19 hours ago), so within the next 6 hours other builds should hopefully pass.

https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=41738 was fixed 10 hours ago.

**Comment by pitrou** [comment]
That seems to have worked indeed, thank you.

**Comment by tytso** [comment]
The e2fsprogs-fuzz builds are now succeeding so I think we close this out now.

Thanks!!
